CREATE DATABASE IF NOT EXISTS mm_login_server;
CREATE DATABASE IF NOT EXISTS mm_game_server;
CREATE DATABASE IF NOT EXISTS mm_game_server_2;
CREATE DATABASE IF NOT EXISTS mm_game_server_3;
CREATE DATABASE IF NOT EXISTS mm_game_server_4;
