// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_message.proto

package msg_server_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MSGID int32

const (
	MSGID_NONE                          MSGID = 0
	MSGID_G2C_GAME_SERVER_REGISTER      MSGID = 20000
	MSGID_G2C_GAME_SERVER_UNREDISTER    MSGID = 20001
	MSGID_C2G_LOGIN_SERVER_LIST         MSGID = 20010
	MSGID_C2G_NEW_LOGIN_SERVER_ADD      MSGID = 20011
	MSGID_C2G_LOGIN_SERVER_REMOVE       MSGID = 20012
	MSGID_G2L_GAME_SERVER_REGISTER      MSGID = 21000
	MSGID_G2L_GAME_SERVER_UNREGISTER    MSGID = 21001
	MSGID_L2G_DISCONNECT_NOTIFY         MSGID = 21002
	MSGID_L2G_SYNC_ACCOUNT_TOKEN        MSGID = 21003
	MSGID_L2G_BIND_NEW_ACCOUNT_REQUEST  MSGID = 21100
	MSGID_G2L_BIND_NEW_ACCOUNT_RESPONSE MSGID = 21101
	MSGID_G2L_ACCOUNT_LOGOUT_NOTIFY     MSGID = 21200
	MSGID_G2L_ACCOUNT_BAN               MSGID = 21300
	MSGID_L2C_LOGIN_SERVER_REGISTER     MSGID = 22004
	MSGID_L2C_LOGIN_SERVER_UNREGISTER   MSGID = 22005
	MSGID_L2C_GET_PLAYER_ACC_INFO       MSGID = 22006
	MSGID_C2L_PLAYER_ACC_INFO           MSGID = 23007
)

var MSGID_name = map[int32]string{
	0:     "NONE",
	20000: "G2C_GAME_SERVER_REGISTER",
	20001: "G2C_GAME_SERVER_UNREDISTER",
	20010: "C2G_LOGIN_SERVER_LIST",
	20011: "C2G_NEW_LOGIN_SERVER_ADD",
	20012: "C2G_LOGIN_SERVER_REMOVE",
	21000: "G2L_GAME_SERVER_REGISTER",
	21001: "G2L_GAME_SERVER_UNREGISTER",
	21002: "L2G_DISCONNECT_NOTIFY",
	21003: "L2G_SYNC_ACCOUNT_TOKEN",
	21100: "L2G_BIND_NEW_ACCOUNT_REQUEST",
	21101: "G2L_BIND_NEW_ACCOUNT_RESPONSE",
	21200: "G2L_ACCOUNT_LOGOUT_NOTIFY",
	21300: "G2L_ACCOUNT_BAN",
	22004: "L2C_LOGIN_SERVER_REGISTER",
	22005: "L2C_LOGIN_SERVER_UNREGISTER",
	22006: "L2C_GET_PLAYER_ACC_INFO",
	23007: "C2L_PLAYER_ACC_INFO",
}

var MSGID_value = map[string]int32{
	"NONE":                          0,
	"G2C_GAME_SERVER_REGISTER":      20000,
	"G2C_GAME_SERVER_UNREDISTER":    20001,
	"C2G_LOGIN_SERVER_LIST":         20010,
	"C2G_NEW_LOGIN_SERVER_ADD":      20011,
	"C2G_LOGIN_SERVER_REMOVE":       20012,
	"G2L_GAME_SERVER_REGISTER":      21000,
	"G2L_GAME_SERVER_UNREGISTER":    21001,
	"L2G_DISCONNECT_NOTIFY":         21002,
	"L2G_SYNC_ACCOUNT_TOKEN":        21003,
	"L2G_BIND_NEW_ACCOUNT_REQUEST":  21100,
	"G2L_BIND_NEW_ACCOUNT_RESPONSE": 21101,
	"G2L_ACCOUNT_LOGOUT_NOTIFY":     21200,
	"G2L_ACCOUNT_BAN":               21300,
	"L2C_LOGIN_SERVER_REGISTER":     22004,
	"L2C_LOGIN_SERVER_UNREGISTER":   22005,
	"L2C_GET_PLAYER_ACC_INFO":       22006,
	"C2L_PLAYER_ACC_INFO":           23007,
}

func (x MSGID) String() string {
	return proto.EnumName(MSGID_name, int32(x))
}

func (MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{0}
}

type LoginServerInfo struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	ListenGameIP         string   `protobuf:"bytes,3,opt,name=ListenGameIP,proto3" json:"ListenGameIP,omitempty"`
	ListenClientIP       string   `protobuf:"bytes,4,opt,name=ListenClientIP,proto3" json:"ListenClientIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginServerInfo) Reset()         { *m = LoginServerInfo{} }
func (m *LoginServerInfo) String() string { return proto.CompactTextString(m) }
func (*LoginServerInfo) ProtoMessage()    {}
func (*LoginServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{0}
}

func (m *LoginServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginServerInfo.Unmarshal(m, b)
}
func (m *LoginServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginServerInfo.Marshal(b, m, deterministic)
}
func (m *LoginServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginServerInfo.Merge(m, src)
}
func (m *LoginServerInfo) XXX_Size() int {
	return xxx_messageInfo_LoginServerInfo.Size(m)
}
func (m *LoginServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginServerInfo proto.InternalMessageInfo

func (m *LoginServerInfo) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *LoginServerInfo) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *LoginServerInfo) GetListenGameIP() string {
	if m != nil {
		return m.ListenGameIP
	}
	return ""
}

func (m *LoginServerInfo) GetListenClientIP() string {
	if m != nil {
		return m.ListenClientIP
	}
	return ""
}

type PlayerBaseInfo struct {
	Lvl                  int32    `protobuf:"varint,1,opt,name=Lvl,proto3" json:"Lvl,omitempty"`
	Exp                  int32    `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	CurMaxStage          int32    `protobuf:"varint,3,opt,name=CurMaxStage,proto3" json:"CurMaxStage,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Icon                 int32    `protobuf:"varint,5,opt,name=Icon,proto3" json:"Icon,omitempty"`
	CustomIcon           string   `protobuf:"bytes,6,opt,name=CustomIcon,proto3" json:"CustomIcon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerBaseInfo) Reset()         { *m = PlayerBaseInfo{} }
func (m *PlayerBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerBaseInfo) ProtoMessage()    {}
func (*PlayerBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{1}
}

func (m *PlayerBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBaseInfo.Unmarshal(m, b)
}
func (m *PlayerBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBaseInfo.Marshal(b, m, deterministic)
}
func (m *PlayerBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBaseInfo.Merge(m, src)
}
func (m *PlayerBaseInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerBaseInfo.Size(m)
}
func (m *PlayerBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBaseInfo proto.InternalMessageInfo

func (m *PlayerBaseInfo) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *PlayerBaseInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *PlayerBaseInfo) GetCurMaxStage() int32 {
	if m != nil {
		return m.CurMaxStage
	}
	return 0
}

func (m *PlayerBaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerBaseInfo) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *PlayerBaseInfo) GetCustomIcon() string {
	if m != nil {
		return m.CustomIcon
	}
	return ""
}

// 玩家某一个关卡的信息
type PlayerStageInfo struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Lvl                  int32    `protobuf:"varint,4,opt,name=Lvl,proto3" json:"Lvl,omitempty"`
	Icon                 string   `protobuf:"bytes,5,opt,name=Icon,proto3" json:"Icon,omitempty"`
	CustomIcon           string   `protobuf:"bytes,6,opt,name=CustomIcon,proto3" json:"CustomIcon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStageInfo) Reset()         { *m = PlayerStageInfo{} }
func (m *PlayerStageInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerStageInfo) ProtoMessage()    {}
func (*PlayerStageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{2}
}

func (m *PlayerStageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStageInfo.Unmarshal(m, b)
}
func (m *PlayerStageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStageInfo.Marshal(b, m, deterministic)
}
func (m *PlayerStageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStageInfo.Merge(m, src)
}
func (m *PlayerStageInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerStageInfo.Size(m)
}
func (m *PlayerStageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStageInfo proto.InternalMessageInfo

func (m *PlayerStageInfo) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerStageInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *PlayerStageInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerStageInfo) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *PlayerStageInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PlayerStageInfo) GetCustomIcon() string {
	if m != nil {
		return m.CustomIcon
	}
	return ""
}

/// game->center GameServer注册
type G2CGameServerRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	ListenRoomIP         string   `protobuf:"bytes,3,opt,name=ListenRoomIP,proto3" json:"ListenRoomIP,omitempty"`
	ListenClientIP       string   `protobuf:"bytes,4,opt,name=ListenClientIP,proto3" json:"ListenClientIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2CGameServerRegister) Reset()         { *m = G2CGameServerRegister{} }
func (m *G2CGameServerRegister) String() string { return proto.CompactTextString(m) }
func (*G2CGameServerRegister) ProtoMessage()    {}
func (*G2CGameServerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{3}
}

func (m *G2CGameServerRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2CGameServerRegister.Unmarshal(m, b)
}
func (m *G2CGameServerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2CGameServerRegister.Marshal(b, m, deterministic)
}
func (m *G2CGameServerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2CGameServerRegister.Merge(m, src)
}
func (m *G2CGameServerRegister) XXX_Size() int {
	return xxx_messageInfo_G2CGameServerRegister.Size(m)
}
func (m *G2CGameServerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_G2CGameServerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_G2CGameServerRegister proto.InternalMessageInfo

func (m *G2CGameServerRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *G2CGameServerRegister) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *G2CGameServerRegister) GetListenRoomIP() string {
	if m != nil {
		return m.ListenRoomIP
	}
	return ""
}

func (m *G2CGameServerRegister) GetListenClientIP() string {
	if m != nil {
		return m.ListenClientIP
	}
	return ""
}

/// game->center GameServer注销
type G2CGameServerUnRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2CGameServerUnRegister) Reset()         { *m = G2CGameServerUnRegister{} }
func (m *G2CGameServerUnRegister) String() string { return proto.CompactTextString(m) }
func (*G2CGameServerUnRegister) ProtoMessage()    {}
func (*G2CGameServerUnRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{4}
}

func (m *G2CGameServerUnRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2CGameServerUnRegister.Unmarshal(m, b)
}
func (m *G2CGameServerUnRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2CGameServerUnRegister.Marshal(b, m, deterministic)
}
func (m *G2CGameServerUnRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2CGameServerUnRegister.Merge(m, src)
}
func (m *G2CGameServerUnRegister) XXX_Size() int {
	return xxx_messageInfo_G2CGameServerUnRegister.Size(m)
}
func (m *G2CGameServerUnRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_G2CGameServerUnRegister.DiscardUnknown(m)
}

var xxx_messageInfo_G2CGameServerUnRegister proto.InternalMessageInfo

func (m *G2CGameServerUnRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

// center->game 同步服务器列表(仅仅会在收到注册消息的时候发这条消息)
type C2GLoginServerList struct {
	ServerList           []*LoginServerInfo `protobuf:"bytes,1,rep,name=ServerList,proto3" json:"ServerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *C2GLoginServerList) Reset()         { *m = C2GLoginServerList{} }
func (m *C2GLoginServerList) String() string { return proto.CompactTextString(m) }
func (*C2GLoginServerList) ProtoMessage()    {}
func (*C2GLoginServerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{5}
}

func (m *C2GLoginServerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GLoginServerList.Unmarshal(m, b)
}
func (m *C2GLoginServerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GLoginServerList.Marshal(b, m, deterministic)
}
func (m *C2GLoginServerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GLoginServerList.Merge(m, src)
}
func (m *C2GLoginServerList) XXX_Size() int {
	return xxx_messageInfo_C2GLoginServerList.Size(m)
}
func (m *C2GLoginServerList) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GLoginServerList.DiscardUnknown(m)
}

var xxx_messageInfo_C2GLoginServerList proto.InternalMessageInfo

func (m *C2GLoginServerList) GetServerList() []*LoginServerInfo {
	if m != nil {
		return m.ServerList
	}
	return nil
}

// center->game 新的得LoginServer增加
type C2GNewLoginServerAdd struct {
	Server               *LoginServerInfo `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *C2GNewLoginServerAdd) Reset()         { *m = C2GNewLoginServerAdd{} }
func (m *C2GNewLoginServerAdd) String() string { return proto.CompactTextString(m) }
func (*C2GNewLoginServerAdd) ProtoMessage()    {}
func (*C2GNewLoginServerAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{6}
}

func (m *C2GNewLoginServerAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GNewLoginServerAdd.Unmarshal(m, b)
}
func (m *C2GNewLoginServerAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GNewLoginServerAdd.Marshal(b, m, deterministic)
}
func (m *C2GNewLoginServerAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GNewLoginServerAdd.Merge(m, src)
}
func (m *C2GNewLoginServerAdd) XXX_Size() int {
	return xxx_messageInfo_C2GNewLoginServerAdd.Size(m)
}
func (m *C2GNewLoginServerAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GNewLoginServerAdd.DiscardUnknown(m)
}

var xxx_messageInfo_C2GNewLoginServerAdd proto.InternalMessageInfo

func (m *C2GNewLoginServerAdd) GetServer() *LoginServerInfo {
	if m != nil {
		return m.Server
	}
	return nil
}

// center->game GameServer断开连接
type C2GLoginServerRemove struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GLoginServerRemove) Reset()         { *m = C2GLoginServerRemove{} }
func (m *C2GLoginServerRemove) String() string { return proto.CompactTextString(m) }
func (*C2GLoginServerRemove) ProtoMessage()    {}
func (*C2GLoginServerRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{7}
}

func (m *C2GLoginServerRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GLoginServerRemove.Unmarshal(m, b)
}
func (m *C2GLoginServerRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GLoginServerRemove.Marshal(b, m, deterministic)
}
func (m *C2GLoginServerRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GLoginServerRemove.Merge(m, src)
}
func (m *C2GLoginServerRemove) XXX_Size() int {
	return xxx_messageInfo_C2GLoginServerRemove.Size(m)
}
func (m *C2GLoginServerRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GLoginServerRemove.DiscardUnknown(m)
}

var xxx_messageInfo_C2GLoginServerRemove proto.InternalMessageInfo

func (m *C2GLoginServerRemove) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

/// game->login game注册
type G2LGameServerRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	ListenClientIP       string   `protobuf:"bytes,3,opt,name=ListenClientIP,proto3" json:"ListenClientIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2LGameServerRegister) Reset()         { *m = G2LGameServerRegister{} }
func (m *G2LGameServerRegister) String() string { return proto.CompactTextString(m) }
func (*G2LGameServerRegister) ProtoMessage()    {}
func (*G2LGameServerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{8}
}

func (m *G2LGameServerRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2LGameServerRegister.Unmarshal(m, b)
}
func (m *G2LGameServerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2LGameServerRegister.Marshal(b, m, deterministic)
}
func (m *G2LGameServerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2LGameServerRegister.Merge(m, src)
}
func (m *G2LGameServerRegister) XXX_Size() int {
	return xxx_messageInfo_G2LGameServerRegister.Size(m)
}
func (m *G2LGameServerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_G2LGameServerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_G2LGameServerRegister proto.InternalMessageInfo

func (m *G2LGameServerRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *G2LGameServerRegister) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *G2LGameServerRegister) GetListenClientIP() string {
	if m != nil {
		return m.ListenClientIP
	}
	return ""
}

/// game->login game注销
type G2LGameServerUnRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	Reason               int32    `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2LGameServerUnRegister) Reset()         { *m = G2LGameServerUnRegister{} }
func (m *G2LGameServerUnRegister) String() string { return proto.CompactTextString(m) }
func (*G2LGameServerUnRegister) ProtoMessage()    {}
func (*G2LGameServerUnRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{9}
}

func (m *G2LGameServerUnRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2LGameServerUnRegister.Unmarshal(m, b)
}
func (m *G2LGameServerUnRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2LGameServerUnRegister.Marshal(b, m, deterministic)
}
func (m *G2LGameServerUnRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2LGameServerUnRegister.Merge(m, src)
}
func (m *G2LGameServerUnRegister) XXX_Size() int {
	return xxx_messageInfo_G2LGameServerUnRegister.Size(m)
}
func (m *G2LGameServerUnRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_G2LGameServerUnRegister.DiscardUnknown(m)
}

var xxx_messageInfo_G2LGameServerUnRegister proto.InternalMessageInfo

func (m *G2LGameServerUnRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *G2LGameServerUnRegister) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

/// login->game 强制断开
type L2GDissconnectNotify struct {
	Reason               int32    `protobuf:"varint,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2GDissconnectNotify) Reset()         { *m = L2GDissconnectNotify{} }
func (m *L2GDissconnectNotify) String() string { return proto.CompactTextString(m) }
func (*L2GDissconnectNotify) ProtoMessage()    {}
func (*L2GDissconnectNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{10}
}

func (m *L2GDissconnectNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2GDissconnectNotify.Unmarshal(m, b)
}
func (m *L2GDissconnectNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2GDissconnectNotify.Marshal(b, m, deterministic)
}
func (m *L2GDissconnectNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2GDissconnectNotify.Merge(m, src)
}
func (m *L2GDissconnectNotify) XXX_Size() int {
	return xxx_messageInfo_L2GDissconnectNotify.Size(m)
}
func (m *L2GDissconnectNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_L2GDissconnectNotify.DiscardUnknown(m)
}

var xxx_messageInfo_L2GDissconnectNotify proto.InternalMessageInfo

func (m *L2GDissconnectNotify) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

/// login->game 同步账号临时密码
type L2GSyncAccountToken struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	PlayerId             int64    `protobuf:"varint,4,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2GSyncAccountToken) Reset()         { *m = L2GSyncAccountToken{} }
func (m *L2GSyncAccountToken) String() string { return proto.CompactTextString(m) }
func (*L2GSyncAccountToken) ProtoMessage()    {}
func (*L2GSyncAccountToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{11}
}

func (m *L2GSyncAccountToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2GSyncAccountToken.Unmarshal(m, b)
}
func (m *L2GSyncAccountToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2GSyncAccountToken.Marshal(b, m, deterministic)
}
func (m *L2GSyncAccountToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2GSyncAccountToken.Merge(m, src)
}
func (m *L2GSyncAccountToken) XXX_Size() int {
	return xxx_messageInfo_L2GSyncAccountToken.Size(m)
}
func (m *L2GSyncAccountToken) XXX_DiscardUnknown() {
	xxx_messageInfo_L2GSyncAccountToken.DiscardUnknown(m)
}

var xxx_messageInfo_L2GSyncAccountToken proto.InternalMessageInfo

func (m *L2GSyncAccountToken) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *L2GSyncAccountToken) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *L2GSyncAccountToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *L2GSyncAccountToken) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

/// login->game 绑定新账号
type L2GBindNewAccountRequest struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	NewAccount           string   `protobuf:"bytes,3,opt,name=NewAccount,proto3" json:"NewAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2GBindNewAccountRequest) Reset()         { *m = L2GBindNewAccountRequest{} }
func (m *L2GBindNewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*L2GBindNewAccountRequest) ProtoMessage()    {}
func (*L2GBindNewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{12}
}

func (m *L2GBindNewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2GBindNewAccountRequest.Unmarshal(m, b)
}
func (m *L2GBindNewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2GBindNewAccountRequest.Marshal(b, m, deterministic)
}
func (m *L2GBindNewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2GBindNewAccountRequest.Merge(m, src)
}
func (m *L2GBindNewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_L2GBindNewAccountRequest.Size(m)
}
func (m *L2GBindNewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_L2GBindNewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_L2GBindNewAccountRequest proto.InternalMessageInfo

func (m *L2GBindNewAccountRequest) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *L2GBindNewAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *L2GBindNewAccountRequest) GetNewAccount() string {
	if m != nil {
		return m.NewAccount
	}
	return ""
}

type G2LBindNewAccountResponse struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	NewAccount           string   `protobuf:"bytes,3,opt,name=NewAccount,proto3" json:"NewAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2LBindNewAccountResponse) Reset()         { *m = G2LBindNewAccountResponse{} }
func (m *G2LBindNewAccountResponse) String() string { return proto.CompactTextString(m) }
func (*G2LBindNewAccountResponse) ProtoMessage()    {}
func (*G2LBindNewAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{13}
}

func (m *G2LBindNewAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2LBindNewAccountResponse.Unmarshal(m, b)
}
func (m *G2LBindNewAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2LBindNewAccountResponse.Marshal(b, m, deterministic)
}
func (m *G2LBindNewAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2LBindNewAccountResponse.Merge(m, src)
}
func (m *G2LBindNewAccountResponse) XXX_Size() int {
	return xxx_messageInfo_G2LBindNewAccountResponse.Size(m)
}
func (m *G2LBindNewAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_G2LBindNewAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_G2LBindNewAccountResponse proto.InternalMessageInfo

func (m *G2LBindNewAccountResponse) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *G2LBindNewAccountResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *G2LBindNewAccountResponse) GetNewAccount() string {
	if m != nil {
		return m.NewAccount
	}
	return ""
}

// game->login 登出游戏通知
type G2LAccountLogoutNotify struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2LAccountLogoutNotify) Reset()         { *m = G2LAccountLogoutNotify{} }
func (m *G2LAccountLogoutNotify) String() string { return proto.CompactTextString(m) }
func (*G2LAccountLogoutNotify) ProtoMessage()    {}
func (*G2LAccountLogoutNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{14}
}

func (m *G2LAccountLogoutNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2LAccountLogoutNotify.Unmarshal(m, b)
}
func (m *G2LAccountLogoutNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2LAccountLogoutNotify.Marshal(b, m, deterministic)
}
func (m *G2LAccountLogoutNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2LAccountLogoutNotify.Merge(m, src)
}
func (m *G2LAccountLogoutNotify) XXX_Size() int {
	return xxx_messageInfo_G2LAccountLogoutNotify.Size(m)
}
func (m *G2LAccountLogoutNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_G2LAccountLogoutNotify.DiscardUnknown(m)
}

var xxx_messageInfo_G2LAccountLogoutNotify proto.InternalMessageInfo

func (m *G2LAccountLogoutNotify) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// game->login 封号
type G2LAccountBan struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	BanOrFree            int32    `protobuf:"varint,2,opt,name=BanOrFree,proto3" json:"BanOrFree,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	PlayerId             int32    `protobuf:"varint,4,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2LAccountBan) Reset()         { *m = G2LAccountBan{} }
func (m *G2LAccountBan) String() string { return proto.CompactTextString(m) }
func (*G2LAccountBan) ProtoMessage()    {}
func (*G2LAccountBan) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{15}
}

func (m *G2LAccountBan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2LAccountBan.Unmarshal(m, b)
}
func (m *G2LAccountBan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2LAccountBan.Marshal(b, m, deterministic)
}
func (m *G2LAccountBan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2LAccountBan.Merge(m, src)
}
func (m *G2LAccountBan) XXX_Size() int {
	return xxx_messageInfo_G2LAccountBan.Size(m)
}
func (m *G2LAccountBan) XXX_DiscardUnknown() {
	xxx_messageInfo_G2LAccountBan.DiscardUnknown(m)
}

var xxx_messageInfo_G2LAccountBan proto.InternalMessageInfo

func (m *G2LAccountBan) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *G2LAccountBan) GetBanOrFree() int32 {
	if m != nil {
		return m.BanOrFree
	}
	return 0
}

func (m *G2LAccountBan) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *G2LAccountBan) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

/// Login->Center Login注册
type L2CLoginServerRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	ListenGameIP         string   `protobuf:"bytes,3,opt,name=ListenGameIP,proto3" json:"ListenGameIP,omitempty"`
	ListenClientIP       string   `protobuf:"bytes,4,opt,name=ListenClientIP,proto3" json:"ListenClientIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2CLoginServerRegister) Reset()         { *m = L2CLoginServerRegister{} }
func (m *L2CLoginServerRegister) String() string { return proto.CompactTextString(m) }
func (*L2CLoginServerRegister) ProtoMessage()    {}
func (*L2CLoginServerRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{16}
}

func (m *L2CLoginServerRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2CLoginServerRegister.Unmarshal(m, b)
}
func (m *L2CLoginServerRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2CLoginServerRegister.Marshal(b, m, deterministic)
}
func (m *L2CLoginServerRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2CLoginServerRegister.Merge(m, src)
}
func (m *L2CLoginServerRegister) XXX_Size() int {
	return xxx_messageInfo_L2CLoginServerRegister.Size(m)
}
func (m *L2CLoginServerRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_L2CLoginServerRegister.DiscardUnknown(m)
}

var xxx_messageInfo_L2CLoginServerRegister proto.InternalMessageInfo

func (m *L2CLoginServerRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *L2CLoginServerRegister) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *L2CLoginServerRegister) GetListenGameIP() string {
	if m != nil {
		return m.ListenGameIP
	}
	return ""
}

func (m *L2CLoginServerRegister) GetListenClientIP() string {
	if m != nil {
		return m.ListenClientIP
	}
	return ""
}

/// Login->Center Login注销
type L2CLoginServerUnRegister struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	Reason               int32    `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2CLoginServerUnRegister) Reset()         { *m = L2CLoginServerUnRegister{} }
func (m *L2CLoginServerUnRegister) String() string { return proto.CompactTextString(m) }
func (*L2CLoginServerUnRegister) ProtoMessage()    {}
func (*L2CLoginServerUnRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{17}
}

func (m *L2CLoginServerUnRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2CLoginServerUnRegister.Unmarshal(m, b)
}
func (m *L2CLoginServerUnRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2CLoginServerUnRegister.Marshal(b, m, deterministic)
}
func (m *L2CLoginServerUnRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2CLoginServerUnRegister.Merge(m, src)
}
func (m *L2CLoginServerUnRegister) XXX_Size() int {
	return xxx_messageInfo_L2CLoginServerUnRegister.Size(m)
}
func (m *L2CLoginServerUnRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_L2CLoginServerUnRegister.DiscardUnknown(m)
}

var xxx_messageInfo_L2CLoginServerUnRegister proto.InternalMessageInfo

func (m *L2CLoginServerUnRegister) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *L2CLoginServerUnRegister) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

/// Login->Center 获取玩家账号Id和所在大厅信息
type L2CGetPlayerAccInfo struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2CGetPlayerAccInfo) Reset()         { *m = L2CGetPlayerAccInfo{} }
func (m *L2CGetPlayerAccInfo) String() string { return proto.CompactTextString(m) }
func (*L2CGetPlayerAccInfo) ProtoMessage()    {}
func (*L2CGetPlayerAccInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{18}
}

func (m *L2CGetPlayerAccInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2CGetPlayerAccInfo.Unmarshal(m, b)
}
func (m *L2CGetPlayerAccInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2CGetPlayerAccInfo.Marshal(b, m, deterministic)
}
func (m *L2CGetPlayerAccInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2CGetPlayerAccInfo.Merge(m, src)
}
func (m *L2CGetPlayerAccInfo) XXX_Size() int {
	return xxx_messageInfo_L2CGetPlayerAccInfo.Size(m)
}
func (m *L2CGetPlayerAccInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_L2CGetPlayerAccInfo.DiscardUnknown(m)
}

var xxx_messageInfo_L2CGetPlayerAccInfo proto.InternalMessageInfo

func (m *L2CGetPlayerAccInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

/// Center->Login 玩家账号信息回复
type C2LPlayerAccInfo struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	GameId               int32    `protobuf:"varint,3,opt,name=GameId,proto3" json:"GameId,omitempty"`
	GameIP               string   `protobuf:"bytes,4,opt,name=GameIP,proto3" json:"GameIP,omitempty"`
	IfForbidLogin        int32    `protobuf:"varint,5,opt,name=IfForbidLogin,proto3" json:"IfForbidLogin,omitempty"`
	ForbidEndTime        string   `protobuf:"bytes,6,opt,name=ForbidEndTime,proto3" json:"ForbidEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2LPlayerAccInfo) Reset()         { *m = C2LPlayerAccInfo{} }
func (m *C2LPlayerAccInfo) String() string { return proto.CompactTextString(m) }
func (*C2LPlayerAccInfo) ProtoMessage()    {}
func (*C2LPlayerAccInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{19}
}

func (m *C2LPlayerAccInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2LPlayerAccInfo.Unmarshal(m, b)
}
func (m *C2LPlayerAccInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2LPlayerAccInfo.Marshal(b, m, deterministic)
}
func (m *C2LPlayerAccInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2LPlayerAccInfo.Merge(m, src)
}
func (m *C2LPlayerAccInfo) XXX_Size() int {
	return xxx_messageInfo_C2LPlayerAccInfo.Size(m)
}
func (m *C2LPlayerAccInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_C2LPlayerAccInfo.DiscardUnknown(m)
}

var xxx_messageInfo_C2LPlayerAccInfo proto.InternalMessageInfo

func (m *C2LPlayerAccInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *C2LPlayerAccInfo) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2LPlayerAccInfo) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *C2LPlayerAccInfo) GetGameIP() string {
	if m != nil {
		return m.GameIP
	}
	return ""
}

func (m *C2LPlayerAccInfo) GetIfForbidLogin() int32 {
	if m != nil {
		return m.IfForbidLogin
	}
	return 0
}

func (m *C2LPlayerAccInfo) GetForbidEndTime() string {
	if m != nil {
		return m.ForbidEndTime
	}
	return ""
}

/// 玩家上线
type SetPlayerOnOffline struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	TongId               int32    `protobuf:"varint,2,opt,name=TongId,proto3" json:"TongId,omitempty"`
	OnOffLine            int32    `protobuf:"varint,3,opt,name=OnOffLine,proto3" json:"OnOffLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPlayerOnOffline) Reset()         { *m = SetPlayerOnOffline{} }
func (m *SetPlayerOnOffline) String() string { return proto.CompactTextString(m) }
func (*SetPlayerOnOffline) ProtoMessage()    {}
func (*SetPlayerOnOffline) Descriptor() ([]byte, []int) {
	return fileDescriptor_2557c738574e6de0, []int{20}
}

func (m *SetPlayerOnOffline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPlayerOnOffline.Unmarshal(m, b)
}
func (m *SetPlayerOnOffline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPlayerOnOffline.Marshal(b, m, deterministic)
}
func (m *SetPlayerOnOffline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPlayerOnOffline.Merge(m, src)
}
func (m *SetPlayerOnOffline) XXX_Size() int {
	return xxx_messageInfo_SetPlayerOnOffline.Size(m)
}
func (m *SetPlayerOnOffline) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPlayerOnOffline.DiscardUnknown(m)
}

var xxx_messageInfo_SetPlayerOnOffline proto.InternalMessageInfo

func (m *SetPlayerOnOffline) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *SetPlayerOnOffline) GetTongId() int32 {
	if m != nil {
		return m.TongId
	}
	return 0
}

func (m *SetPlayerOnOffline) GetOnOffLine() int32 {
	if m != nil {
		return m.OnOffLine
	}
	return 0
}

func init() {
	proto.RegisterEnum("msg.server_message.MSGID", MSGID_name, MSGID_value)
	proto.RegisterType((*LoginServerInfo)(nil), "msg.server_message.LoginServerInfo")
	proto.RegisterType((*PlayerBaseInfo)(nil), "msg.server_message.PlayerBaseInfo")
	proto.RegisterType((*PlayerStageInfo)(nil), "msg.server_message.PlayerStageInfo")
	proto.RegisterType((*G2CGameServerRegister)(nil), "msg.server_message.G2CGameServerRegister")
	proto.RegisterType((*G2CGameServerUnRegister)(nil), "msg.server_message.G2CGameServerUnRegister")
	proto.RegisterType((*C2GLoginServerList)(nil), "msg.server_message.C2GLoginServerList")
	proto.RegisterType((*C2GNewLoginServerAdd)(nil), "msg.server_message.C2GNewLoginServerAdd")
	proto.RegisterType((*C2GLoginServerRemove)(nil), "msg.server_message.C2GLoginServerRemove")
	proto.RegisterType((*G2LGameServerRegister)(nil), "msg.server_message.G2LGameServerRegister")
	proto.RegisterType((*G2LGameServerUnRegister)(nil), "msg.server_message.G2LGameServerUnRegister")
	proto.RegisterType((*L2GDissconnectNotify)(nil), "msg.server_message.L2GDissconnectNotify")
	proto.RegisterType((*L2GSyncAccountToken)(nil), "msg.server_message.L2GSyncAccountToken")
	proto.RegisterType((*L2GBindNewAccountRequest)(nil), "msg.server_message.L2GBindNewAccountRequest")
	proto.RegisterType((*G2LBindNewAccountResponse)(nil), "msg.server_message.G2LBindNewAccountResponse")
	proto.RegisterType((*G2LAccountLogoutNotify)(nil), "msg.server_message.G2LAccountLogoutNotify")
	proto.RegisterType((*G2LAccountBan)(nil), "msg.server_message.G2LAccountBan")
	proto.RegisterType((*L2CLoginServerRegister)(nil), "msg.server_message.L2CLoginServerRegister")
	proto.RegisterType((*L2CLoginServerUnRegister)(nil), "msg.server_message.L2CLoginServerUnRegister")
	proto.RegisterType((*L2CGetPlayerAccInfo)(nil), "msg.server_message.L2CGetPlayerAccInfo")
	proto.RegisterType((*C2LPlayerAccInfo)(nil), "msg.server_message.C2LPlayerAccInfo")
	proto.RegisterType((*SetPlayerOnOffline)(nil), "msg.server_message.SetPlayerOnOffline")
}

func init() { proto.RegisterFile("server_message.proto", fileDescriptor_2557c738574e6de0) }

var fileDescriptor_2557c738574e6de0 = []byte{
	// 1049 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x67, 0x36, 0x4d, 0xd9, 0xbe, 0x65, 0x77, 0xad, 0xd9, 0x6e, 0x37, 0xfb, 0xaf, 0x14, 0x2f,
	0x42, 0x15, 0x87, 0x22, 0x19, 0x71, 0xe2, 0x94, 0x4c, 0xdc, 0x91, 0xc5, 0xd4, 0x2e, 0xb6, 0xb3,
	0xa8, 0x27, 0x2b, 0x9b, 0x4c, 0x22, 0x8b, 0x66, 0xdc, 0xc6, 0x49, 0x77, 0x2b, 0x84, 0xb8, 0xf2,
	0xe7, 0x13, 0x20, 0x15, 0x58, 0xa4, 0xc0, 0x81, 0x72, 0x83, 0x8f, 0xc0, 0x07, 0xe0, 0x1b, 0xf0,
	0x05, 0xe0, 0x06, 0x9c, 0xd1, 0x8c, 0xc7, 0x89, 0x9d, 0x94, 0xaa, 0x40, 0xb9, 0xcd, 0xfb, 0xbd,
	0xdf, 0xbc, 0xf9, 0xbd, 0xf7, 0xe6, 0x79, 0x0c, 0xab, 0x29, 0x1f, 0x1e, 0xf1, 0x61, 0x34, 0xe0,
	0x69, 0xda, 0xee, 0xf3, 0xad, 0x83, 0x61, 0x32, 0x4a, 0x30, 0x1e, 0xa4, 0xfd, 0xad, 0xb2, 0xc7,
	0xfc, 0x1c, 0xc1, 0x4d, 0x96, 0xf4, 0x63, 0x11, 0x28, 0xdc, 0x11, 0xbd, 0x04, 0xdf, 0x83, 0xab,
	0xda, 0xea, 0xd6, 0xd0, 0x06, 0xda, 0xac, 0xfa, 0x53, 0x1b, 0xaf, 0x03, 0x64, 0x6b, 0xb7, 0x3d,
	0xe0, 0xb5, 0x2b, 0x1b, 0x68, 0x73, 0xc5, 0x2f, 0x20, 0xd8, 0x84, 0x97, 0x58, 0x9c, 0x8e, 0xb8,
	0xa0, 0xed, 0x01, 0x77, 0x76, 0x6b, 0x15, 0xc5, 0x28, 0x61, 0xf8, 0x35, 0xb8, 0x91, 0xd9, 0x64,
	0x3f, 0xe6, 0x62, 0xe4, 0xec, 0xd6, 0x96, 0x14, 0x6b, 0x0e, 0x35, 0xbf, 0x44, 0x70, 0x63, 0x77,
	0xbf, 0x7d, 0xcc, 0x87, 0x8d, 0x76, 0xca, 0x95, 0x34, 0x03, 0x2a, 0xec, 0x68, 0x5f, 0xab, 0x92,
	0x4b, 0x89, 0xd8, 0xcf, 0x0e, 0x94, 0x92, 0xaa, 0x2f, 0x97, 0x78, 0x03, 0xae, 0x91, 0xf1, 0x70,
	0xa7, 0xfd, 0x2c, 0x18, 0xb5, 0xfb, 0x5c, 0x29, 0xa8, 0xfa, 0x45, 0x08, 0x63, 0x58, 0x52, 0xf2,
	0xb3, 0x63, 0xd5, 0x5a, 0x62, 0x4e, 0x27, 0x11, 0xb5, 0xaa, 0xa2, 0xab, 0xb5, 0x4c, 0x96, 0x8c,
	0xd3, 0x51, 0x32, 0x50, 0x9e, 0xe5, 0x2c, 0xd9, 0x19, 0x62, 0x7e, 0x81, 0xe0, 0x66, 0x26, 0x50,
	0xc5, 0xcd, 0x8b, 0x97, 0x41, 0xb3, 0xe2, 0xe5, 0x36, 0x5e, 0x85, 0x6a, 0xd0, 0x49, 0x86, 0x5c,
	0xab, 0xcd, 0x8c, 0xa9, 0x9a, 0x4a, 0x41, 0x8d, 0xce, 0x73, 0x69, 0x96, 0x67, 0x51, 0xdf, 0xca,
	0x05, 0xf5, 0x7d, 0x85, 0xe0, 0x36, 0xb5, 0x88, 0x2c, 0x7b, 0xd6, 0x22, 0x9f, 0xf7, 0x65, 0x89,
	0x87, 0x97, 0xd3, 0x62, 0x3f, 0x49, 0x06, 0xf3, 0x2d, 0xce, 0xb0, 0x0b, 0xb7, 0xf8, 0x2d, 0xb8,
	0x53, 0x12, 0xd8, 0x12, 0x17, 0x91, 0x68, 0xee, 0x01, 0x26, 0x16, 0x2d, 0xdc, 0x5b, 0x19, 0x16,
	0x93, 0x5c, 0xb8, 0xb4, 0x6a, 0x68, 0xa3, 0xb2, 0x79, 0xcd, 0x7a, 0xb4, 0xb5, 0x78, 0xe9, 0xb7,
	0xe6, 0x2e, 0xbc, 0x5f, 0xd8, 0x66, 0x06, 0xb0, 0x4a, 0x2c, 0xea, 0xf2, 0xa7, 0x05, 0x52, 0xbd,
	0xdb, 0xc5, 0x6f, 0xc3, 0x72, 0x66, 0x28, 0x31, 0x17, 0x0c, 0xac, 0xb7, 0x98, 0x96, 0x0a, 0x5a,
	0xf0, 0xfa, 0x7c, 0x90, 0x1c, 0xf1, 0x73, 0x73, 0xfc, 0x40, 0xf6, 0x8e, 0x5d, 0x72, 0xef, 0x16,
	0xfb, 0x52, 0x39, 0xb3, 0x2f, 0x3b, 0xb2, 0x2f, 0xec, 0x9f, 0xf6, 0x05, 0xaf, 0xc1, 0xb2, 0xcf,
	0xdb, 0x69, 0x22, 0xf4, 0x0d, 0xd7, 0x96, 0xb9, 0x05, 0xab, 0xcc, 0xa2, 0xcd, 0x38, 0x4d, 0x3b,
	0x89, 0x10, 0xbc, 0x33, 0x72, 0x93, 0x51, 0xdc, 0x3b, 0x2e, 0xf0, 0x51, 0x89, 0xff, 0x21, 0xdc,
	0x62, 0x16, 0x0d, 0x8e, 0x45, 0xa7, 0xde, 0xe9, 0x24, 0x63, 0x31, 0x0a, 0x93, 0xf7, 0xb9, 0x90,
	0x47, 0xb7, 0x44, 0x7c, 0x38, 0xe6, 0xfa, 0xe8, 0x15, 0x7f, 0x6a, 0xe3, 0x1a, 0xbc, 0xa8, 0xb9,
	0x3a, 0xed, 0xdc, 0x94, 0x53, 0xa7, 0xb6, 0xeb, 0x54, 0xab, 0xd3, 0x58, 0xd3, 0x39, 0x95, 0x77,
	0xb3, 0x32, 0x9b, 0x53, 0xf3, 0x00, 0x6a, 0xcc, 0xa2, 0x8d, 0x58, 0x74, 0x5d, 0xfe, 0x54, 0x87,
	0xf1, 0xf9, 0xe1, 0x98, 0xa7, 0xa3, 0x7f, 0xa9, 0x61, 0x1d, 0x60, 0x16, 0x4a, 0x0b, 0x29, 0x20,
	0xe6, 0x21, 0xdc, 0xa5, 0x16, 0x9b, 0x3f, 0x31, 0x3d, 0x48, 0x44, 0xca, 0xff, 0xa7, 0x23, 0x2d,
	0x58, 0xa3, 0x16, 0xd3, 0x16, 0x4b, 0xfa, 0xc9, 0x38, 0xef, 0x4a, 0x21, 0x26, 0x2a, 0xc5, 0x34,
	0x3f, 0x82, 0xeb, 0xb3, 0x3d, 0x8d, 0xf6, 0xf9, 0x1d, 0x79, 0x00, 0x2b, 0x8d, 0xb6, 0xf0, 0x86,
	0xdb, 0x43, 0x9e, 0x7f, 0xf1, 0x66, 0x40, 0xf1, 0x90, 0x4a, 0x59, 0xf8, 0x7c, 0x67, 0x0a, 0x5f,
	0x50, 0xf3, 0x39, 0x82, 0x35, 0x66, 0x91, 0xd2, 0x24, 0x5d, 0xe6, 0x27, 0xed, 0x12, 0x5e, 0x2d,
	0x57, 0x5e, 0x9e, 0xa2, 0xc2, 0xff, 0x38, 0x3b, 0x6f, 0xc8, 0x59, 0x20, 0x94, 0x8f, 0xb2, 0x22,
	0xd4, 0x3b, 0x1d, 0xf5, 0xce, 0xfc, 0x7d, 0x93, 0x7e, 0x42, 0x60, 0x10, 0x8b, 0x5d, 0x90, 0x5e,
	0x2a, 0xf7, 0x95, 0xf2, 0x20, 0x48, 0x4d, 0x2a, 0xfb, 0xae, 0x7e, 0x45, 0xb5, 0x35, 0xc5, 0xf3,
	0x1a, 0x68, 0x0b, 0xbf, 0x0a, 0xd7, 0x9d, 0xde, 0x76, 0x32, 0x7c, 0x12, 0x77, 0x55, 0x01, 0xf4,
	0x6b, 0x5a, 0x06, 0x25, 0x2b, 0x33, 0x6d, 0xd1, 0x0d, 0xe3, 0x01, 0xd7, 0x2f, 0x57, 0x19, 0x34,
	0x7b, 0x80, 0x83, 0x3c, 0x69, 0x4f, 0x78, 0xbd, 0xde, 0x7e, 0x2c, 0xf8, 0xb9, 0xcf, 0xeb, 0x1a,
	0x2c, 0x87, 0x89, 0xe8, 0xeb, 0x3c, 0xaa, 0xbe, 0xb6, 0xe4, 0x45, 0x54, 0x01, 0x58, 0x2c, 0xf2,
	0xdf, 0x81, 0x19, 0xf0, 0xfa, 0xe9, 0x12, 0x54, 0x77, 0x02, 0xea, 0x34, 0xf1, 0x55, 0x58, 0x72,
	0x3d, 0xd7, 0x36, 0x5e, 0xc0, 0xeb, 0x50, 0xa3, 0x16, 0x89, 0x68, 0x7d, 0xc7, 0x8e, 0x02, 0xdb,
	0x7f, 0x6c, 0xfb, 0x91, 0x6f, 0x53, 0x27, 0x08, 0x6d, 0xdf, 0x78, 0x7e, 0x82, 0xf0, 0x06, 0xdc,
	0x9b, 0xf7, 0xb7, 0x5c, 0xdf, 0x6e, 0x66, 0x8c, 0xaf, 0x4f, 0x10, 0xbe, 0x0f, 0xb7, 0x89, 0x45,
	0x23, 0xe6, 0x51, 0xc7, 0xcd, 0x29, 0xcc, 0x09, 0x42, 0xe3, 0xbb, 0x13, 0x24, 0xc3, 0x4b, 0xa7,
	0x6b, 0xbf, 0x57, 0x26, 0xd4, 0x9b, 0x4d, 0xe3, 0xf4, 0x04, 0xe1, 0x87, 0x70, 0x67, 0x61, 0xb3,
	0x6f, 0xef, 0x78, 0x8f, 0x6d, 0xe3, 0xfb, 0x6c, 0x3b, 0xb5, 0xd8, 0xd9, 0xea, 0x3e, 0x9e, 0x68,
	0x75, 0x6c, 0x41, 0x9d, 0x66, 0x7c, 0x32, 0x51, 0xea, 0x98, 0x45, 0xa3, 0xa6, 0x13, 0x10, 0xcf,
	0x75, 0x6d, 0x12, 0x46, 0xae, 0x17, 0x3a, 0xdb, 0x7b, 0xc6, 0xa7, 0x13, 0x84, 0x1f, 0xc8, 0x11,
	0xa3, 0x51, 0xb0, 0xe7, 0x92, 0xa8, 0x4e, 0x88, 0xd7, 0x72, 0xc3, 0x28, 0xf4, 0xde, 0xb1, 0x5d,
	0xe3, 0xb3, 0x09, 0xc2, 0x26, 0x3c, 0x90, 0xde, 0x86, 0xe3, 0x36, 0x55, 0x02, 0x39, 0xc3, 0xb7,
	0xdf, 0x6d, 0xd9, 0x41, 0x68, 0xfc, 0x3a, 0x41, 0xf8, 0x11, 0x3c, 0x94, 0x02, 0xce, 0xe0, 0x04,
	0xbb, 0x9e, 0x1b, 0xd8, 0xc6, 0x6f, 0x13, 0x84, 0x5f, 0x56, 0x9f, 0xbc, 0xa9, 0x8f, 0x79, 0xd4,
	0x6b, 0x4d, 0x75, 0xfc, 0xfc, 0x0d, 0xc2, 0xb7, 0xe1, 0x66, 0x91, 0xd0, 0xa8, 0xbb, 0xc6, 0x8f,
	0xdf, 0xaa, 0x7d, 0xcc, 0x22, 0xf3, 0xc5, 0xd1, 0xc9, 0xfd, 0x7e, 0x8a, 0xf0, 0x2b, 0x70, 0x7f,
	0x81, 0x50, 0xc8, 0xff, 0x8f, 0x53, 0x55, 0x60, 0x49, 0xa1, 0x76, 0x18, 0xed, 0xb2, 0xfa, 0x9e,
	0x2c, 0x3d, 0x21, 0x91, 0xe3, 0x6e, 0x7b, 0xc6, 0x9f, 0xa7, 0x08, 0xdf, 0x85, 0x5b, 0xc4, 0x62,
	0x0b, 0xae, 0x5f, 0x7e, 0x40, 0x4f, 0x96, 0xd5, 0xaf, 0xf4, 0x9b, 0x7f, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0x0c, 0xa2, 0x52, 0x62, 0x0b, 0x00, 0x00,
}
